### ISSUE TITLE
UPNP not working. (Minecraft 1.21.1 Fabric 0.16.7)

### ISSUE THREAD

**Issue by SkyExploreWasTaken** [PigCart/dedicatedmcupnp#7]
The console tells me that it can't open the TCP port 25565 (MC)
[latest.log](https://github.com/user-attachments/files/17434066/latest.log)

**Comment by PigCart** [comment]
try again with [the new v2.0.2](https://modrinth.com/mod/dedicatedmcupnp/version/2.0.2)

**Comment by SkyExploreWasTaken** [comment]
Okay I will try

**Comment by PigCart** [comment]
closing from inactivity
